# Generated by Django 5.1.1 on 2024-10-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_text_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('LS', 'Lifestyle'), ('HL', 'Health'), ('PR', 'Programming'), ('FM', 'Family'), ('MG', 'Management'), ('TR', 'Travel'), ('WK', 'Work')], max_length=2),
        ),
    ]
