# Generated by Django 5.1.1 on 2024-10-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Lifestyle', 'Lifestyle'), ('Health', 'Health'), ('Programming', 'Programming'), ('Family', 'Family'), ('Management', 'Management'), ('Travel', 'Travel'), ('Work', 'Work')], default='Programming', max_length=11),
        ),
    ]
