# Generated by Django 5.1.1 on 2024-10-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_user_image_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_image',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
