# Generated by Django 5.1.1 on 2024-10-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
