# Generated by Django 5.1.1 on 2026-05-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_autosaved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
