# Generated by Django 5.1.1 on 2024-10-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.TextField(choices=[('Lifestyle', 'Lifestyle'), ('Health', 'Health'), ('Programming', 'Programming'), ('Family', 'Family'), ('Managemant', 'Managemant'), ('Travel', 'Travel'), ('Work', 'Work')], default='Programming', max_length=12),
        ),
    ]
