# Generated by Django 5.1.1 on 2024-10-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_title_post_text_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Lifestyle', 'Lifestyle'), ('Health', 'Health'), ('Programming', 'Programming'), ('Family', 'Family'), ('Management', 'Management'), ('Travel', 'Travel'), ('Work', 'Work')], max_length=11),
        ),
    ]
